### ISSUE TITLE
Change cursor to reflect UI component states

### ISSUE THREAD

**Issue by https123456789** [Spelunking-Studios/The-Caverns#15]
This would mean that when a UI component (lets say a `Button`) has a particular state activated, the system cursor will be updated to reflect the state. For example, when a `Button` component has the `hover` or `clicked` state, the system cursor should be a pointer and upon being `unhovered` or `unclicked`, the cursor will return to the system default. This is not a high priority, as it is purely ascetics, but it shouldn't be hard to implement. @LGgameLAB what are your thoughts?

**Comment by LGgameLAB** [comment]
It would have to be done on the "object-side" to save our game checking if the mouse collides with a bunch of objects (RIP CPU) so I suppose you could if you wished. On the other hand, I was thinking of replacing the standard mouse icon with something cooler (Maybe a stone colored mouse) but as you said I find this very low priority so I wouldn't worry about this.
